[Mon Apr 14 03:39:36 PM CEST 2025] Bestanden gedetecteerd in /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive, start verwerking...
[Mon Apr 14 03:39:36 PM CEST 2025] Nieuw bestand gedetecteerd: /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive/SC.1.3.6.1.4.1.49282.99.1.20250407111731.303881.1.1
[Mon Apr 14 03:39:36 PM CEST 2025] Bestandsgrootte: 3080158 bytes
[Mon Apr 14 03:39:36 PM CEST 2025] Bestandseigenaar: isala
[Mon Apr 14 03:39:36 PM CEST 2025] Bestandstype: /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive/SC.1.3.6.1.4.1.49282.99.1.20250407111731.303881.1.1: DICOM medical imaging data
[Mon Apr 14 03:39:36 PM CEST 2025] Start verwerkingsscript: python3 /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Core/processing_script.py /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive/SC.1.3.6.1.4.1.49282.99.1.20250407111731.303881.1.1
‚ùå Input pad is geen geldige map: IsalaOCR/DICOM_node_simulator/Receive
Traceback (most recent call last):
  File "/home/isala/ocr/IsalaOCR/modules/run.py", line 6, in <module>
    from dcm2jpg import process_dicom_folder
  File "/home/isala/ocr/IsalaOCR/modules/dcm2jpg.py", line 5, in <module>
    import SimpleITK as sitk
ModuleNotFoundError: No module named 'SimpleITK'
Bestand /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive/SC.1.3.6.1.4.1.49282.99.1.20250407111731.303881.1.1 succesvol gelogd.
Start run.py voor bestand: /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive/SC.1.3.6.1.4.1.49282.99.1.20250407111731.303881.1.1
Fout bij uitvoeren van run.py: Command '['/usr/bin/python3', '/home/isala/ocr/IsalaOCR/modules/run.py', '/home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive/SC.1.3.6.1.4.1.49282.99.1.20250407111731.303881.1.1']' returned non-zero exit status 1.
[Mon Apr 14 03:39:36 PM CEST 2025] Verwerkingsscript succesvol uitgevoerd voor: /home/isala/ocr/IsalaOCR/DICOM_node_simulator/Receive/SC.1.3.6.1.4.1.49282.99.1.20250407111731.303881.1.1
